// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Revisions.Subjects {
    func revisionID(_ revisionID: Int) -> WithRevisionID {
        WithRevisionID(path: "\(path)/\(revisionID)")
    }

    struct WithRevisionID {
        /// Path: `/v0/revisions/subjects/{revision_id}`
        public let path: String

        /// Get Subject Revision
        public var get: Request<BangumiKit.SubjectRevision> {
            Request(path: path, method: "GET", id: "getSubjectRevisionByRevisionId")
        }
    }
}
