// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0 {
    var indices: Indices {
        Indices(path: path + "/indices")
    }

    struct Indices {
        /// Path: `/v0/indices`
        public let path: String

        /// Create a new index
        public var post: Request<BangumiKit.Index> {
            Request(path: path, method: "POST", id: "newIndex")
        }
    }
}
