// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Subjects.WithSubjectID {
    var characters: Characters {
        Characters(path: path + "/characters")
    }

    struct Characters {
        /// Path: `/v0/subjects/{subject_id}/characters`
        public let path: String

        /// Get Subject Characters
        public var get: Request<[BangumiKit.RelatedCharacter]> {
            Request(path: path, method: "GET", id: "getRelatedCharactersBySubjectId")
        }
    }
}
