// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Characters.WithCharacterID {
    var subjects: Subjects {
        Subjects(path: path + "/subjects")
    }

    struct Subjects {
        /// Path: `/v0/characters/{character_id}/subjects`
        public let path: String

        /// Get character related subjects
        public var get: Request<[BangumiKit.V0RelatedSubject]> {
            Request(path: path, method: "GET", id: "getRelatedSubjectsByCharacterId")
        }
    }
}
