// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Users.WithUsername.Collections.Minus.Characters {
    func characterID(_ characterID: Int) -> WithCharacterID {
        WithCharacterID(path: "\(path)/\(characterID)")
    }

    struct WithCharacterID {
        /// Path: `/v0/users/{username}/collections/-/characters/{character_id}`
        public let path: String

        /// 获取用户单个角色收藏信息
        public var get: Request<BangumiKit.UserCharacterCollection> {
            Request(path: path, method: "GET", id: "getUserCharacterCollection")
        }
    }
}
