// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Characters.WithCharacterID {
    var persons: Persons {
        Persons(path: path + "/persons")
    }

    struct Persons {
        /// Path: `/v0/characters/{character_id}/persons`
        public let path: String

        /// Get character related persons
        public var get: Request<[BangumiKit.CharacterPerson]> {
            Request(path: path, method: "GET", id: "getRelatedPersonsByCharacterId")
        }
    }
}
