// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Indices {
    func indexID(_ indexID: Int) -> WithIndexID {
        WithIndexID(path: "\(path)/\(indexID)")
    }

    struct WithIndexID {
        /// Path: `/v0/indices/{index_id}`
        public let path: String

        /// Get Index By ID
        public var get: Request<BangumiKit.Index> {
            Request(path: path, method: "GET", id: "getIndexById")
        }

        /// Edit index's information
        public func put(_ body: BangumiKit.IndexBasicInfo? = nil) -> Request<BangumiKit.Index> {
            Request(path: path, method: "PUT", body: body, id: "editIndexById")
        }
    }
}
