// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Persons.WithPersonID {
    var subjects: Subjects {
        Subjects(path: path + "/subjects")
    }

    struct Subjects {
        /// Path: `/v0/persons/{person_id}/subjects`
        public let path: String

        /// Get person related subjects
        public var get: Request<[BangumiKit.V0RelatedSubject]> {
            Request(path: path, method: "GET", id: "getRelatedSubjectsByPersonId")
        }
    }
}
