// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Subjects.WithSubjectID {
    var subjects: Subjects {
        Subjects(path: path + "/subjects")
    }

    struct Subjects {
        /// Path: `/v0/subjects/{subject_id}/subjects`
        public let path: String

        /// Get Subject Relations
        public var get: Request<[BangumiKit.V0SubjectRelation]> {
            Request(path: path, method: "GET", id: "getRelatedSubjectsBySubjectId")
        }
    }
}
