// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Users {
    func username(_ username: String) -> WithUsername {
        WithUsername(path: "\(path)/\(username)")
    }

    struct WithUsername {
        /// Path: `/v0/users/{username}`
        public let path: String

        /// Get User by name
        ///
        /// 获取用户信息
        public var get: Request<BangumiKit.User> {
            Request(path: path, method: "GET", id: "getUserByName")
        }
    }
}
