// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Subjects.WithSubjectID {
    var persons: Persons {
        Persons(path: path + "/persons")
    }

    struct Persons {
        /// Path: `/v0/subjects/{subject_id}/persons`
        public let path: String

        /// Get Subject Persons
        public var get: Request<[BangumiKit.RelatedPerson]> {
            Request(path: path, method: "GET", id: "getRelatedPersonsBySubjectId")
        }
    }
}
