// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Persons.WithPersonID {
    var image: Image {
        Image(path: path + "/image")
    }

    struct Image {
        /// Path: `/v0/persons/{person_id}/image`
        public let path: String

        /// Get Person Image
        public func get(type: String) -> Request<Void> {
            Request(path: path, method: "GET", query: [("type", type)], id: "getPersonImageById")
        }
    }
}
