// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths {
    static var calendar: Calendar {
        Calendar(path: "/calendar")
    }

    struct Calendar {
        /// Path: `/calendar`
        public let path: String

        /// 每日放送
        public var get: Request<[GetResponseItem]> {
            Request(path: path, method: "GET", id: "getCalendar")
        }

        public struct GetResponseItem: Decodable {
            public var weekday: Weekday?
            public var items: [BangumiKit.LegacySubjectSmall]?

            public struct Weekday: Decodable {
                /// Example: "Mon"
                public var en: String?
                /// Example: "星期一"
                public var cn: String?
                /// Example: "月耀日"
                public var ja: String?
                public var id: Int?

                public init(en: String? = nil, cn: String? = nil, ja: String? = nil, id: Int? = nil) {
                    self.en = en
                    self.cn = cn
                    self.ja = ja
                    self.id = id
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.en = try values.decodeIfPresent(String.self, forKey: "en")
                    self.cn = try values.decodeIfPresent(String.self, forKey: "cn")
                    self.ja = try values.decodeIfPresent(String.self, forKey: "ja")
                    self.id = try values.decodeIfPresent(Int.self, forKey: "id")
                }
            }

            public init(weekday: Weekday? = nil, items: [BangumiKit.LegacySubjectSmall]? = nil) {
                self.weekday = weekday
                self.items = items
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.weekday = try values.decodeIfPresent(Weekday.self, forKey: "weekday")
                self.items = try values.decodeIfPresent([BangumiKit.LegacySubjectSmall].self, forKey: "items")
            }
        }
    }
}
