// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Users.WithUsername.Collections.Minus.Persons {
    func personID(_ personID: Int) -> WithPersonID {
        WithPersonID(path: "\(path)/\(personID)")
    }

    struct WithPersonID {
        /// Path: `/v0/users/{username}/collections/-/persons/{person_id}`
        public let path: String

        /// 获取用户单个人物收藏信息
        public var get: Request<BangumiKit.UserPersonCollection> {
            Request(path: path, method: "GET", id: "getUserPersonCollection")
        }
    }
}
