// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Subjects.WithSubjectID {
    var image: Image {
        Image(path: path + "/image")
    }

    struct Image {
        /// Path: `/v0/subjects/{subject_id}/image`
        public let path: String

        /// Get Subject Image
        public func get(type: String) -> Request<Void> {
            Request(path: path, method: "GET", query: [("type", type)], id: "getSubjectImageById")
        }
    }
}
