// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Indices.WithIndexID {
    var subjects: Subjects {
        Subjects(path: path + "/subjects")
    }

    struct Subjects {
        /// Path: `/v0/indices/{index_id}/subjects`
        public let path: String

        /// Get Index Subjects
        public func get(parameters: GetParameters? = nil) -> Request<Void> {
            Request(path: path, method: "GET", query: parameters?.asQuery, id: "getIndexSubjectsByIndexId")
        }

        public struct GetParameters {
            /// SubjectType
            ///
            /// 条目类型
            /// - `1` 为 书籍
            /// - `2` 为 动画
            /// - `3` 为 音乐
            /// - `4` 为 游戏
            /// - `6` 为 三次元
            ///
            /// 没有 `5`
            public var type: Int?
            public var limit: Int?
            public var offset: Int?

            public init(type: Int? = nil, limit: Int? = nil, offset: Int? = nil) {
                self.type = type
                self.limit = limit
                self.offset = offset
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(type, forKey: "type")
                encoder.encode(limit, forKey: "limit")
                encoder.encode(offset, forKey: "offset")
                return encoder.items
            }
        }

        /// Add a subject to Index
        public func post(_ body: BangumiKit.IndexSubjectAddInfo? = nil) -> Request<Void> {
            Request(path: path, method: "POST", body: body, id: "addSubjectToIndexByIndexId")
        }
    }
}
