// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Persons {
    func personID(_ personID: Int) -> WithPersonID {
        WithPersonID(path: "\(path)/\(personID)")
    }

    struct WithPersonID {
        /// Path: `/v0/persons/{person_id}`
        public let path: String

        /// Get Person
        ///
        /// Cache with 60s
        public var get: Request<BangumiKit.PersonDetail> {
            Request(path: path, method: "GET", id: "getPersonById")
        }
    }
}
