// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Characters {
    func characterID(_ characterID: Int) -> WithCharacterID {
        WithCharacterID(path: "\(path)/\(characterID)")
    }

    struct WithCharacterID {
        /// Path: `/v0/characters/{character_id}`
        public let path: String

        /// Get Character Detail
        ///
        /// Cache with 60s
        public var get: Request<BangumiKit.Character> {
            Request(path: path, method: "GET", id: "getCharacterById")
        }
    }
}
