// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Users.WithUsername.Collections.Minus {
    var characters: Characters {
        Characters(path: path + "/characters")
    }

    struct Characters {
        /// Path: `/v0/users/{username}/collections/-/characters`
        public let path: String

        /// 获取用户角色收藏列表
        public var get: Request<BangumiKit.PagedUserCharacterCollection> {
            Request(path: path, method: "GET", id: "getUserCharacterCollections")
        }
    }
}
