// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0 {
    var characters: Characters {
        Characters(path: path + "/characters")
    }

    struct Characters {
        /// Path: `/v0/characters`
        public let path: String
    }
}
