// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Users.WithUsername {
    var avatar: Avatar {
        Avatar(path: path + "/avatar")
    }

    struct Avatar {
        /// Path: `/v0/users/{username}/avatar`
        public let path: String

        /// Get User Avatar by name
        ///
        /// 获取用户头像，302 重定向至头像地址，设置了 username 之后无法使用 UID 查询。
        public func get(type: String) -> Request<Void> {
            Request(path: path, method: "GET", query: [("type", type)], id: "getUserAvatarByName")
        }
    }
}
