// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Persons.WithPersonID {
    var collect: Collect {
        Collect(path: path + "/collect")
    }

    struct Collect {
        /// Path: `/v0/persons/{person_id}/collect`
        public let path: String

        /// Collect person for current user
        ///
        /// 为当前用户收藏人物
        public var post: Request<Void> {
            Request(path: path, method: "POST", id: "collectPersonByPersonIdAndUserId")
        }

        /// Uncollect person for current user
        ///
        /// 为当前用户取消收藏人物
        public var delete: Request<Void> {
            Request(path: path, method: "DELETE", id: "uncollectPersonByPersonIdAndUserId")
        }
    }
}
