// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Users.Minus.Collections.Minus {
    var episodes: Episodes {
        Episodes(path: path + "/episodes")
    }

    struct Episodes {
        /// Path: `/v0/users/-/collections/-/episodes`
        public let path: String
    }
}
