// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Revisions.Episodes {
    func revisionID(_ revisionID: Int) -> WithRevisionID {
        WithRevisionID(path: "\(path)/\(revisionID)")
    }

    struct WithRevisionID {
        /// Path: `/v0/revisions/episodes/{revision_id}`
        public let path: String

        /// Get Episode Revision
        public var get: Request<BangumiKit.DetailedRevision> {
            Request(path: path, method: "GET", id: "getEpisodeRevisionByRevisionId")
        }
    }
}
