// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Revisions {
    var persons: Persons {
        Persons(path: path + "/persons")
    }

    struct Persons {
        /// Path: `/v0/revisions/persons`
        public let path: String

        /// Get Person Revisions
        public func get(parameters: GetParameters) -> Request<BangumiKit.PagedRevision> {
            Request(path: path, method: "GET", query: parameters.asQuery, id: "getPersonRevisions")
        }

        public struct GetParameters {
            public var personID: Int
            public var limit: Int?
            public var offset: Int?

            public init(personID: Int, limit: Int? = nil, offset: Int? = nil) {
                self.personID = personID
                self.limit = limit
                self.offset = offset
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(personID, forKey: "person_id")
                encoder.encode(limit, forKey: "limit")
                encoder.encode(offset, forKey: "offset")
                return encoder.items
            }
        }
    }
}
