// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Revisions {
    var episodes: Episodes {
        Episodes(path: path + "/episodes")
    }

    struct Episodes {
        /// Path: `/v0/revisions/episodes`
        public let path: String

        /// Get Episode Revisions
        public func get(parameters: GetParameters) -> Request<BangumiKit.PagedRevision> {
            Request(path: path, method: "GET", query: parameters.asQuery, id: "getEpisodeRevisions")
        }

        public struct GetParameters {
            public var episodeID: Int
            public var limit: Int?
            public var offset: Int?

            public init(episodeID: Int, limit: Int? = nil, offset: Int? = nil) {
                self.episodeID = episodeID
                self.limit = limit
                self.offset = offset
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(episodeID, forKey: "episode_id")
                encoder.encode(limit, forKey: "limit")
                encoder.encode(offset, forKey: "offset")
                return encoder.items
            }
        }
    }
}
