// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Users.Minus.Collections {
    var minus: Minus {
        Minus(path: path + "/-")
    }

    struct Minus {
        /// Path: `/v0/users/-/collections/-`
        public let path: String
    }
}
