// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths {
    static var v0: V0 {
        V0(path: "/v0")
    }

    struct V0 {
        /// Path: `/v0`
        public let path: String
    }
}
