// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0 {
    var revisions: Revisions {
        Revisions(path: path + "/revisions")
    }

    struct Revisions {
        /// Path: `/v0/revisions`
        public let path: String
    }
}
