// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0 {
    var users: Users {
        Users(path: path + "/users")
    }

    struct Users {
        /// Path: `/v0/users`
        public let path: String
    }
}
