// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Revisions {
    var characters: Characters {
        Characters(path: path + "/characters")
    }

    struct Characters {
        /// Path: `/v0/revisions/characters`
        public let path: String

        /// Get Character Revisions
        public func get(parameters: GetParameters) -> Request<BangumiKit.PagedRevision> {
            Request(path: path, method: "GET", query: parameters.asQuery, id: "getCharacterRevisions")
        }

        public struct GetParameters {
            public var characterID: Int
            public var limit: Int?
            public var offset: Int?

            public init(characterID: Int, limit: Int? = nil, offset: Int? = nil) {
                self.characterID = characterID
                self.limit = limit
                self.offset = offset
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(characterID, forKey: "character_id")
                encoder.encode(limit, forKey: "limit")
                encoder.encode(offset, forKey: "offset")
                return encoder.items
            }
        }
    }
}
