// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Indices.WithIndexID.Subjects {
    func subjectID(_ subjectID: Int) -> WithSubjectID {
        WithSubjectID(path: "\(path)/\(subjectID)")
    }

    struct WithSubjectID {
        /// Path: `/v0/indices/{index_id}/subjects/{subject_id}`
        public let path: String

        /// Edit subject information in a index
        ///
        /// 如果条目不存在于目录，会创建该条目
        public func put(_ body: BangumiKit.IndexSubjectEditInfo? = nil) -> Request<Void> {
            Request(path: path, method: "PUT", body: body, id: "editIndexSubjectsByIndexIdAndSubjectID")
        }

        /// Delete a subject from a Index
        public var delete: Request<Void> {
            Request(path: path, method: "DELETE", id: "delelteSubjectFromIndexByIndexIdAndSubjectID")
        }
    }
}
