// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Users.WithUsername.Collections {
    func subjectID(_ subjectID: Int) -> WithSubjectID {
        WithSubjectID(path: "\(path)/\(subjectID)")
    }

    struct WithSubjectID {
        /// Path: `/v0/users/{username}/collections/{subject_id}`
        public let path: String

        /// 获取用户单个条目收藏
        ///
        /// 获取对应用户的收藏，查看私有收藏需要 access token
        public var get: Request<BangumiKit.UserSubjectCollection> {
            Request(path: path, method: "GET", id: "getUserCollection")
        }
    }
}
