// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Episodes {
    func episodeID(_ episodeID: Int) -> WithEpisodeID {
        WithEpisodeID(path: "\(path)/\(episodeID)")
    }

    struct WithEpisodeID {
        /// Path: `/v0/episodes/{episode_id}`
        public let path: String

        /// Get Episode
        public var get: Request<BangumiKit.EpisodeDetail> {
            Request(path: path, method: "GET", id: "getEpisodeById")
        }
    }
}
