// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths {
    static var search: Search {
        Search(path: "/search")
    }

    struct Search {
        /// Path: `/search`
        public let path: String
    }
}
