// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Users.Minus {
    var collections: Collections {
        Collections(path: path + "/collections")
    }

    struct Collections {
        /// Path: `/v0/users/-/collections`
        public let path: String
    }
}
