// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Revisions {
    var subjects: Subjects {
        Subjects(path: path + "/subjects")
    }

    struct Subjects {
        /// Path: `/v0/revisions/subjects`
        public let path: String

        /// Get Subject Revisions
        public func get(parameters: GetParameters) -> Request<BangumiKit.PagedRevision> {
            Request(path: path, method: "GET", query: parameters.asQuery, id: "getSubjectRevisions")
        }

        public struct GetParameters {
            public var subjectID: Int
            public var limit: Int?
            public var offset: Int?

            public init(subjectID: Int, limit: Int? = nil, offset: Int? = nil) {
                self.subjectID = subjectID
                self.limit = limit
                self.offset = offset
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(subjectID, forKey: "subject_id")
                encoder.encode(limit, forKey: "limit")
                encoder.encode(offset, forKey: "offset")
                return encoder.items
            }
        }
    }
}
