// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.V0.Indices.WithIndexID {
    var collect: Collect {
        Collect(path: path + "/collect")
    }

    struct Collect {
        /// Path: `/v0/indices/{index_id}/collect`
        public let path: String

        /// Collect index for current user
        ///
        /// 为当前用户收藏一条目录
        public var post: Request<Void> {
            Request(path: path, method: "POST", id: "collectIndexByIndexIdAndUserId")
        }

        /// Uncollect index for current user
        ///
        /// 为当前用户取消收藏一条目录
        public var delete: Request<Void> {
            Request(path: path, method: "DELETE", id: "uncollectIndexByIndexIdAndUserId")
        }
    }
}
