// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

public extension Paths.Search {
    var subject: Subject {
        Subject(path: path + "/subject")
    }

    struct Subject {
        /// Path: `/search/subject`
        public let path: String
    }
}
