// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Collect index for current user
    ///
    /// 为当前用户收藏一条目录
    static public func collectIndexByIndexIDAndUserId(indexID: Int) -> Request<Void> {
        Request(path: "/v0/indices/\(indexID)/collect", method: "POST", id: "collectIndexByIndexIdAndUserId")
    }
}
