// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Collect character for current user
    ///
    /// 为当前用户收藏角色
    static public func collectCharacterByCharacterIDAndUserId(characterID: Int) -> Request<Void> {
        Request(path: "/v0/characters/\(characterID)/collect", method: "POST", id: "collectCharacterByCharacterIdAndUserId")
    }
}
