// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Collect person for current user
    ///
    /// 为当前用户收藏人物
    static public func collectPersonByPersonIDAndUserId(personID: Int) -> Request<Void> {
        Request(path: "/v0/persons/\(personID)/collect", method: "POST", id: "collectPersonByPersonIdAndUserId")
    }
}
