// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Get Character Revisions
    static public func getCharacterRevisions(parameters: GetCharacterRevisionsParameters) -> Request<JellyfinAPI.PagedRevision> {
        Request(path: "/v0/revisions/characters", method: "GET", query: parameters.asQuery, id: "getCharacterRevisions")
    }

    public struct GetCharacterRevisionsParameters {
        public var characterID: Int
        public var limit: Int?
        public var offset: Int?

        public init(characterID: Int, limit: Int? = nil, offset: Int? = nil) {
            self.characterID = characterID
            self.limit = limit
            self.offset = offset
        }

        public var asQuery: [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(characterID, forKey: "character_id")
            encoder.encode(limit, forKey: "limit")
            encoder.encode(offset, forKey: "offset")
            return encoder.items
        }
    }
}
