// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Get Character Detail
    ///
    /// Cache with 60s
    static public func getCharacterByID(characterID: Int) -> Request<JellyfinAPI.Character> {
        Request(path: "/v0/characters/\(characterID)", method: "GET", id: "getCharacterById")
    }
}
