// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Get Index By ID
    static public func getIndexByID(indexID: Int) -> Request<JellyfinAPI.Index> {
        Request(path: "/v0/indices/\(indexID)", method: "GET", id: "getIndexById")
    }
}
