// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Get Person Revision
    static public func getPersonRevisionByRevisionID(revisionID: Int) -> Request<JellyfinAPI.PersonRevision> {
        Request(path: "/v0/revisions/persons/\(revisionID)", method: "GET", id: "getPersonRevisionByRevisionId")
    }
}
