// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Get character related persons
    static public func getRelatedPersonsByCharacterID(characterID: Int) -> Request<[JellyfinAPI.CharacterPerson]> {
        Request(path: "/v0/characters/\(characterID)/persons", method: "GET", id: "getRelatedPersonsByCharacterId")
    }
}
