// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Get character related subjects
    static public func getRelatedSubjectsByCharacterID(characterID: Int) -> Request<[JellyfinAPI.V0RelatedSubject]> {
        Request(path: "/v0/characters/\(characterID)/subjects", method: "GET", id: "getRelatedSubjectsByCharacterId")
    }
}
