// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Get Subject Relations
    static public func getRelatedSubjectsBySubjectID(subjectID: Int) -> Request<[JellyfinAPI.V0SubjectRelation]> {
        Request(path: "/v0/subjects/\(subjectID)/subjects", method: "GET", id: "getRelatedSubjectsBySubjectId")
    }
}
