// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Get person related characters
    static public func getRelatedCharactersByPersonID(personID: Int) -> Request<[BangumiKit.PersonCharacter]> {
        Request(path: "/v0/persons/\(personID)/characters", method: "GET", id: "getRelatedCharactersByPersonId")
    }
}
