// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Get User by name
    ///
    /// 获取用户信息
    static public func getUserByName(username: String) -> Request<JellyfinAPI.User> {
        Request(path: "/v0/users/\(username)", method: "GET", id: "getUserByName")
    }
}
