// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Create a new index
    static public var newIndex: Request<JellyfinAPI.Index> {
        Request(path: "/v0/indices", method: "POST", id: "newIndex")
    }
}
