// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Uncollect person for current user
    ///
    /// 为当前用户取消收藏人物
    static public func uncollectPersonByPersonIDAndUserId(personID: Int) -> Request<Void> {
        Request(path: "/v0/persons/\(personID)/collect", method: "DELETE", id: "uncollectPersonByPersonIdAndUserId")
    }
}
