// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Character: Codable {
    public var id: Int
    public var name: String
    /// 角色，机体，舰船，组织...
    public var type: Int
    /// Object with some size of images, this object maybe `null`
    public var images: PersonImages?
    public var summary: String
    /// Locked
    public var isLocked: Bool
    /// Server parsed infobox, a map from key to string or tuple
    /// null if server infobox is not valid
    public var infobox: [[String: AnyJSON]]?
    /// Parsed from wiki, maybe null
    public var gender: String?
    /// Parsed from wiki, maybe null, `1, 2, 3, 4` for `A, B, AB, O`
    public var bloodType: Int?
    /// Parsed from wiki, maybe `null`
    public var birthYear: Int?
    /// Parsed from wiki, maybe `null`
    public var birthMon: Int?
    /// Parsed from wiki, maybe `null`
    public var birthDay: Int?
    public var stat: Stat

    public init(
        id: Int,
        name: String,
        type: Int,
        images: PersonImages? = nil,
        summary: String,
        isLocked: Bool,
        infobox: [[String: AnyJSON]]? = nil,
        gender: String? = nil,
        bloodType: Int? = nil,
        birthYear: Int? = nil,
        birthMon: Int? = nil,
        birthDay: Int? = nil,
        stat: Stat
    ) {
        self.id = id
        self.name = name
        self.type = type
        self.images = images
        self.summary = summary
        self.isLocked = isLocked
        self.infobox = infobox
        self.gender = gender
        self.bloodType = bloodType
        self.birthYear = birthYear
        self.birthMon = birthMon
        self.birthDay = birthDay
        self.stat = stat
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Int.self, forKey: "id")
        self.name = try values.decode(String.self, forKey: "name")
        self.type = try values.decode(Int.self, forKey: "type")
        self.images = try values.decodeIfPresent(PersonImages.self, forKey: "images")
        self.summary = try values.decode(String.self, forKey: "summary")
        self.isLocked = try values.decode(Bool.self, forKey: "locked")
        self.infobox = try values.decodeIfPresent([[String: AnyJSON]].self, forKey: "infobox")
        self.gender = try values.decodeIfPresent(String.self, forKey: "gender")
        self.bloodType = try values.decodeIfPresent(Int.self, forKey: "blood_type")
        self.birthYear = try values.decodeIfPresent(Int.self, forKey: "birth_year")
        self.birthMon = try values.decodeIfPresent(Int.self, forKey: "birth_mon")
        self.birthDay = try values.decodeIfPresent(Int.self, forKey: "birth_day")
        self.stat = try values.decode(Stat.self, forKey: "stat")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(name, forKey: "name")
        try values.encode(type, forKey: "type")
        try values.encodeIfPresent(images, forKey: "images")
        try values.encode(summary, forKey: "summary")
        try values.encode(isLocked, forKey: "locked")
        try values.encodeIfPresent(infobox, forKey: "infobox")
        try values.encodeIfPresent(gender, forKey: "gender")
        try values.encodeIfPresent(bloodType, forKey: "blood_type")
        try values.encodeIfPresent(birthYear, forKey: "birth_year")
        try values.encodeIfPresent(birthMon, forKey: "birth_mon")
        try values.encodeIfPresent(birthDay, forKey: "birth_day")
        try values.encode(stat, forKey: "stat")
    }
}
