// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CharacterRevisionDataItem: Codable {
    /// Character Infobox
    public var infobox: String
    /// Character Summary
    public var summary: String
    /// Character Name
    public var name: String
    /// RevisionExtra
    public var extra: RevisionExtra

    public init(infobox: String, summary: String, name: String, extra: RevisionExtra) {
        self.infobox = infobox
        self.summary = summary
        self.name = name
        self.extra = extra
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.infobox = try values.decode(String.self, forKey: "infobox")
        self.summary = try values.decode(String.self, forKey: "summary")
        self.name = try values.decode(String.self, forKey: "name")
        self.extra = try values.decode(RevisionExtra.self, forKey: "extra")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(infobox, forKey: "infobox")
        try values.encode(summary, forKey: "summary")
        try values.encode(name, forKey: "name")
        try values.encode(extra, forKey: "extra")
    }
}
