// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// 新增或修改条目的内容，同名字段意义同<a href="#model-Subject">Subject</a>
public struct IndexBasicInfo: Codable {
    public var title: String?
    public var description: String?

    public init(title: String? = nil, description: String? = nil) {
        self.title = title
        self.description = description
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.title = try values.decodeIfPresent(String.self, forKey: "title")
        self.description = try values.decodeIfPresent(String.self, forKey: "description")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(title, forKey: "title")
        try values.encodeIfPresent(description, forKey: "description")
    }
}
