// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// 同名字段意义同<a href="#model-Subject">Subject</a>
public struct IndexSubject: Codable {
    public var id: Int
    public var type: Int
    public var name: String
    public var images: Images?
    /// Example:
    ///
    /// [
    ///   {
    ///     "key" : "简体中文名",
    ///     "value" : "鲁路修·兰佩路基"
    ///   },
    ///   {
    ///     "key" : "别名",
    ///     "value" : [
    ///       {
    ///         "v" : "L.L."
    ///       },
    ///       {
    ///         "v" : "勒鲁什"
    ///       },
    ///       {
    ///         "v" : "鲁鲁修"
    ///       },
    ///       {
    ///         "v" : "ゼロ"
    ///       },
    ///       {
    ///         "v" : "Zero"
    ///       },
    ///       {
    ///         "k" : "英文名",
    ///         "v" : "Lelouch Lamperouge"
    ///       },
    ///       {
    ///         "k" : "第二中文名",
    ///         "v" : "鲁路修·冯·布里塔尼亚"
    ///       },
    ///       {
    ///         "k" : "英文名二",
    ///         "v" : "Lelouch Vie Britannia"
    ///       },
    ///       {
    ///         "k" : "日文名",
    ///         "v" : "ルルーシュ・ヴィ・ブリタニア"
    ///       }
    ///     ]
    ///   },
    ///   {
    ///     "key" : "性别",
    ///     "value" : "男"
    ///   },
    ///   {
    ///     "key" : "生日",
    ///     "value" : "12月5日"
    ///   },
    ///   {
    ///     "key" : "血型",
    ///     "value" : "A型"
    ///   },
    ///   {
    ///     "key" : "身高",
    ///     "value" : "178cm→181cm"
    ///   },
    ///   {
    ///     "key" : "体重",
    ///     "value" : "54kg"
    ///   },
    ///   {
    ///     "key" : "引用来源",
    ///     "value" : "Wikipedia"
    ///   }
    /// ]
    public var infobox: [WikiV0Item]?
    public var date: String?
    public var comment: String
    public var addedAt: Date

    public init(
        id: Int,
        type: Int,
        name: String,
        images: Images? = nil,
        infobox: [WikiV0Item]? = nil,
        date: String? = nil,
        comment: String,
        addedAt: Date
    ) {
        self.id = id
        self.type = type
        self.name = name
        self.images = images
        self.infobox = infobox
        self.date = date
        self.comment = comment
        self.addedAt = addedAt
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Int.self, forKey: "id")
        self.type = try values.decode(Int.self, forKey: "type")
        self.name = try values.decode(String.self, forKey: "name")
        self.images = try values.decodeIfPresent(Images.self, forKey: "images")
        self.infobox = try values.decodeIfPresent([WikiV0Item].self, forKey: "infobox")
        self.date = try values.decodeIfPresent(String.self, forKey: "date")
        self.comment = try values.decode(String.self, forKey: "comment")
        self.addedAt = try values.decode(Date.self, forKey: "added_at")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(type, forKey: "type")
        try values.encode(name, forKey: "name")
        try values.encodeIfPresent(images, forKey: "images")
        try values.encodeIfPresent(infobox, forKey: "infobox")
        try values.encodeIfPresent(date, forKey: "date")
        try values.encode(comment, forKey: "comment")
        try values.encode(addedAt, forKey: "added_at")
    }
}
