// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// IndexBasicInfo
///
/// 新增某条目到目录的请求信息
public struct IndexSubjectAddInfo: Codable {
    public var subjectID: Int?
    /// 排序条件，越小越靠前
    public var sort: Int?
    public var comment: String?

    public init(subjectID: Int? = nil, sort: Int? = nil, comment: String? = nil) {
        self.subjectID = subjectID
        self.sort = sort
        self.comment = comment
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.subjectID = try values.decodeIfPresent(Int.self, forKey: "subject_id")
        self.sort = try values.decodeIfPresent(Int.self, forKey: "sort")
        self.comment = try values.decodeIfPresent(String.self, forKey: "comment")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(subjectID, forKey: "subject_id")
        try values.encodeIfPresent(sort, forKey: "sort")
        try values.encodeIfPresent(comment, forKey: "comment")
    }
}
