// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// IndexBasicInfo
///
/// 修改目录中条目的信息
public struct IndexSubjectEditInfo: Codable {
    /// 排序条件，越小越靠前
    public var sort: Int?
    public var comment: String?

    public init(sort: Int? = nil, comment: String? = nil) {
        self.sort = sort
        self.comment = comment
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.sort = try values.decodeIfPresent(Int.self, forKey: "sort")
        self.comment = try values.decodeIfPresent(String.self, forKey: "comment")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(sort, forKey: "sort")
        try values.encodeIfPresent(comment, forKey: "comment")
    }
}
