// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// 讨论版
public struct LegacyTopic: Codable {
    /// ID
    public var id: Int?
    /// 地址
    public var url: String?
    /// 标题
    public var title: String?
    /// 所属对象（条目） ID
    public var mainID: Int?
    /// 发布时间
    public var timestamp: Int?
    /// 最后回复时间
    public var lastpost: Int?
    /// 回复数
    public var replies: Int?
    /// 用户信息
    public var user: LegacyUser?

    public init(
        id: Int? = nil,
        url: String? = nil,
        title: String? = nil,
        mainID: Int? = nil,
        timestamp: Int? = nil,
        lastpost: Int? = nil,
        replies: Int? = nil,
        user: LegacyUser? = nil
    ) {
        self.id = id
        self.url = url
        self.title = title
        self.mainID = mainID
        self.timestamp = timestamp
        self.lastpost = lastpost
        self.replies = replies
        self.user = user
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(Int.self, forKey: "id")
        self.url = try values.decodeIfPresent(String.self, forKey: "url")
        self.title = try values.decodeIfPresent(String.self, forKey: "title")
        self.mainID = try values.decodeIfPresent(Int.self, forKey: "main_id")
        self.timestamp = try values.decodeIfPresent(Int.self, forKey: "timestamp")
        self.lastpost = try values.decodeIfPresent(Int.self, forKey: "lastpost")
        self.replies = try values.decodeIfPresent(Int.self, forKey: "replies")
        self.user = try values.decodeIfPresent(LegacyUser.self, forKey: "user")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(url, forKey: "url")
        try values.encodeIfPresent(title, forKey: "title")
        try values.encodeIfPresent(mainID, forKey: "main_id")
        try values.encodeIfPresent(timestamp, forKey: "timestamp")
        try values.encodeIfPresent(lastpost, forKey: "lastpost")
        try values.encodeIfPresent(replies, forKey: "replies")
        try values.encodeIfPresent(user, forKey: "user")
    }
}
