// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct LegacySubjectLarge: Codable {
    public var legacySubjectMedium: LegacySubjectMedium
    /// 章节列表
    public var eps: [LegacyEpisode]?
    /// 讨论版
    public var topic: [LegacyTopic]?
    /// 评论日志
    public var blog: [LegacyBlog]?

    public init(
        legacySubjectMedium: LegacySubjectMedium,
        eps: [LegacyEpisode]? = nil,
        topic: [LegacyTopic]? = nil,
        blog: [LegacyBlog]? = nil
    ) {
        self.legacySubjectMedium = legacySubjectMedium
        self.eps = eps
        self.topic = topic
        self.blog = blog
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.legacySubjectMedium = try LegacySubjectMedium(from: decoder)
        self.eps = try values.decodeIfPresent([LegacyEpisode].self, forKey: "eps")
        self.topic = try values.decodeIfPresent([LegacyTopic].self, forKey: "topic")
        self.blog = try values.decodeIfPresent([LegacyBlog].self, forKey: "blog")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(legacySubjectMedium, forKey: "legacySubjectMedium")
        try values.encodeIfPresent(eps, forKey: "eps")
        try values.encodeIfPresent(topic, forKey: "topic")
        try values.encodeIfPresent(blog, forKey: "blog")
    }
}
