// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Page: Codable {
    public var total: Int
    public var limit: Int
    public var offset: Int

    public init(total: Int, limit: Int, offset: Int) {
        self.total = total
        self.limit = limit
        self.offset = offset
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.total = try values.decode(Int.self, forKey: "total")
        self.limit = try values.decode(Int.self, forKey: "limit")
        self.offset = try values.decode(Int.self, forKey: "offset")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(total, forKey: "total")
        try values.encode(limit, forKey: "limit")
        try values.encode(offset, forKey: "offset")
    }
}
