// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PersonImages: Codable {
    public var large: String
    public var medium: String
    public var small: String
    public var grid: String

    public init(large: String, medium: String, small: String, grid: String) {
        self.large = large
        self.medium = medium
        self.small = small
        self.grid = grid
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.large = try values.decode(String.self, forKey: "large")
        self.medium = try values.decode(String.self, forKey: "medium")
        self.small = try values.decode(String.self, forKey: "small")
        self.grid = try values.decode(String.self, forKey: "grid")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(large, forKey: "large")
        try values.encode(medium, forKey: "medium")
        try values.encode(small, forKey: "small")
        try values.encode(grid, forKey: "grid")
    }
}
