// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PersonRevisionDataItem: Codable {
    /// Person Infobox
    public var prsnInfobox: String
    /// Person Summary
    public var prsnSummary: String
    /// PersonRevisionProfession
    public var profession: PersonRevisionProfession
    /// RevisionExtra
    public var extra: RevisionExtra
    /// Person Name
    public var prsnName: String

    public init(prsnInfobox: String, prsnSummary: String, profession: PersonRevisionProfession, extra: RevisionExtra, prsnName: String) {
        self.prsnInfobox = prsnInfobox
        self.prsnSummary = prsnSummary
        self.profession = profession
        self.extra = extra
        self.prsnName = prsnName
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.prsnInfobox = try values.decode(String.self, forKey: "prsn_infobox")
        self.prsnSummary = try values.decode(String.self, forKey: "prsn_summary")
        self.profession = try values.decode(PersonRevisionProfession.self, forKey: "profession")
        self.extra = try values.decode(RevisionExtra.self, forKey: "extra")
        self.prsnName = try values.decode(String.self, forKey: "prsn_name")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(prsnInfobox, forKey: "prsn_infobox")
        try values.encode(prsnSummary, forKey: "prsn_summary")
        try values.encode(profession, forKey: "profession")
        try values.encode(extra, forKey: "extra")
        try values.encode(prsnName, forKey: "prsn_name")
    }
}
