// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PersonRevisionProfession: Codable {
    public var producer: String?
    public var mangaka: String?
    public var artist: String?
    public var seiyu: String?
    public var writer: String?
    public var illustrator: String?
    public var actor: String?

    public init(
        producer: String? = nil,
        mangaka: String? = nil,
        artist: String? = nil,
        seiyu: String? = nil,
        writer: String? = nil,
        illustrator: String? = nil,
        actor: String? = nil
    ) {
        self.producer = producer
        self.mangaka = mangaka
        self.artist = artist
        self.seiyu = seiyu
        self.writer = writer
        self.illustrator = illustrator
        self.actor = actor
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.producer = try values.decodeIfPresent(String.self, forKey: "producer")
        self.mangaka = try values.decodeIfPresent(String.self, forKey: "mangaka")
        self.artist = try values.decodeIfPresent(String.self, forKey: "artist")
        self.seiyu = try values.decodeIfPresent(String.self, forKey: "seiyu")
        self.writer = try values.decodeIfPresent(String.self, forKey: "writer")
        self.illustrator = try values.decodeIfPresent(String.self, forKey: "illustrator")
        self.actor = try values.decodeIfPresent(String.self, forKey: "actor")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(producer, forKey: "producer")
        try values.encodeIfPresent(mangaka, forKey: "mangaka")
        try values.encodeIfPresent(artist, forKey: "artist")
        try values.encodeIfPresent(seiyu, forKey: "seiyu")
        try values.encodeIfPresent(writer, forKey: "writer")
        try values.encodeIfPresent(illustrator, forKey: "illustrator")
        try values.encodeIfPresent(actor, forKey: "actor")
    }
}
