// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct RelatedPerson: Codable {
    public var id: Int
    public var name: String
    /// `1`, `2`, `3` 表示 `个人`, `公司`, `组合`
    public var type: Int
    public var career: [PersonCareer]
    /// Object with some size of images, this object maybe `null`
    public var images: PersonImages?
    public var relation: String
    /// 参与章节/曲目
    public var eps: String

    public init(id: Int, name: String, type: Int, career: [PersonCareer], images: PersonImages? = nil, relation: String, eps: String) {
        self.id = id
        self.name = name
        self.type = type
        self.career = career
        self.images = images
        self.relation = relation
        self.eps = eps
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Int.self, forKey: "id")
        self.name = try values.decode(String.self, forKey: "name")
        self.type = try values.decode(Int.self, forKey: "type")
        self.career = try values.decode([PersonCareer].self, forKey: "career")
        self.images = try values.decodeIfPresent(PersonImages.self, forKey: "images")
        self.relation = try values.decode(String.self, forKey: "relation")
        self.eps = try values.decode(String.self, forKey: "eps")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(name, forKey: "name")
        try values.encode(type, forKey: "type")
        try values.encode(career, forKey: "career")
        try values.encodeIfPresent(images, forKey: "images")
        try values.encode(relation, forKey: "relation")
        try values.encode(eps, forKey: "eps")
    }
}
