// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct SlimSubject: Codable {
    public var id: Int
    public var type: Int
    public var name: String
    public var nameCn: String
    /// Summary
    ///
    /// 截短后的条目描述。
    public var shortSummary: String
    /// Air date in `YYYY-MM-DD` format
    public var date: String?
    public var images: Images
    /// 书籍条目的册数，由旧服务端从wiki中解析
    public var volumes: Int
    /// 由旧服务端从wiki中解析，对于书籍条目为`话数`
    public var eps: Int
    /// Total
    ///
    /// 收藏人数
    public var collectionTotal: Int
    /// 分数
    public var score: Double
    /// 排名
    public var rank: Int
    /// 前 10 个 tag
    public var tags: [SubjectTag]

    public init(
        id: Int,
        type: Int,
        name: String,
        nameCn: String,
        shortSummary: String,
        date: String? = nil,
        images: Images,
        volumes: Int,
        eps: Int,
        collectionTotal: Int,
        score: Double,
        rank: Int,
        tags: [SubjectTag]
    ) {
        self.id = id
        self.type = type
        self.name = name
        self.nameCn = nameCn
        self.shortSummary = shortSummary
        self.date = date
        self.images = images
        self.volumes = volumes
        self.eps = eps
        self.collectionTotal = collectionTotal
        self.score = score
        self.rank = rank
        self.tags = tags
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Int.self, forKey: "id")
        self.type = try values.decode(Int.self, forKey: "type")
        self.name = try values.decode(String.self, forKey: "name")
        self.nameCn = try values.decode(String.self, forKey: "name_cn")
        self.shortSummary = try values.decode(String.self, forKey: "short_summary")
        self.date = try values.decodeIfPresent(String.self, forKey: "date")
        self.images = try values.decode(Images.self, forKey: "images")
        self.volumes = try values.decode(Int.self, forKey: "volumes")
        self.eps = try values.decode(Int.self, forKey: "eps")
        self.collectionTotal = try values.decode(Int.self, forKey: "collection_total")
        self.score = try values.decode(Double.self, forKey: "score")
        self.rank = try values.decode(Int.self, forKey: "rank")
        self.tags = try values.decode([SubjectTag].self, forKey: "tags")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(type, forKey: "type")
        try values.encode(name, forKey: "name")
        try values.encode(nameCn, forKey: "name_cn")
        try values.encode(shortSummary, forKey: "short_summary")
        try values.encodeIfPresent(date, forKey: "date")
        try values.encode(images, forKey: "images")
        try values.encode(volumes, forKey: "volumes")
        try values.encode(eps, forKey: "eps")
        try values.encode(collectionTotal, forKey: "collection_total")
        try values.encode(score, forKey: "score")
        try values.encode(rank, forKey: "rank")
        try values.encode(tags, forKey: "tags")
    }
}
