// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Stat: Codable {
    public var comments: Int
    public var collects: Int

    public init(comments: Int, collects: Int) {
        self.comments = comments
        self.collects = collects
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.comments = try values.decode(Int.self, forKey: "comments")
        self.collects = try values.decode(Int.self, forKey: "collects")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(comments, forKey: "comments")
        try values.encode(collects, forKey: "collects")
    }
}
