// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Tag
public struct SubjectTag: Codable {
    public var name: String
    public var count: Int

    public init(name: String, count: Int) {
        self.name = name
        self.count = count
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.name = try values.decode(String.self, forKey: "name")
        self.count = try values.decode(Int.self, forKey: "count")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(name, forKey: "name")
        try values.encode(count, forKey: "count")
    }
}
