// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// 所有的字段均可选
public struct UserSubjectCollectionModifyPayload: Codable {
    /// 修改条目收藏类型
    public var type: Int?
    /// 评分，`0` 表示删除评分
    public var rate: Int?
    /// 只能用于修改书籍条目进度
    public var epStatus: Int?
    /// 只能用于修改书籍条目进度
    public var volStatus: Int?
    /// 评价
    public var comment: String?
    /// 仅自己可见
    public var isPrivate: Bool?
    /// 标签
    ///
    /// 不传或者 `null` 都会被忽略，传 `[]` 则会删除所有 tag。
    public var tags: [String]?

    public init(
        type: Int? = nil,
        rate: Int? = nil,
        epStatus: Int? = nil,
        volStatus: Int? = nil,
        comment: String? = nil,
        isPrivate: Bool? = nil,
        tags: [String]? = nil
    ) {
        self.type = type
        self.rate = rate
        self.epStatus = epStatus
        self.volStatus = volStatus
        self.comment = comment
        self.isPrivate = isPrivate
        self.tags = tags
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.type = try values.decodeIfPresent(Int.self, forKey: "type")
        self.rate = try values.decodeIfPresent(Int.self, forKey: "rate")
        self.epStatus = try values.decodeIfPresent(Int.self, forKey: "ep_status")
        self.volStatus = try values.decodeIfPresent(Int.self, forKey: "vol_status")
        self.comment = try values.decodeIfPresent(String.self, forKey: "comment")
        self.isPrivate = try values.decodeIfPresent(Bool.self, forKey: "private")
        self.tags = try values.decodeIfPresent([String].self, forKey: "tags")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(type, forKey: "type")
        try values.encodeIfPresent(rate, forKey: "rate")
        try values.encodeIfPresent(epStatus, forKey: "ep_status")
        try values.encodeIfPresent(volStatus, forKey: "vol_status")
        try values.encodeIfPresent(comment, forKey: "comment")
        try values.encodeIfPresent(isPrivate, forKey: "private")
        try values.encodeIfPresent(tags, forKey: "tags")
    }
}
