// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct UserCharacterCollection: Codable {
    public var id: Int
    public var name: String
    /// 角色，机体，舰船，组织...
    public var type: Int
    /// Object with some size of images, this object maybe `null`
    public var images: PersonImages?
    public var createdAt: Date

    public init(id: Int, name: String, type: Int, images: PersonImages? = nil, createdAt: Date) {
        self.id = id
        self.name = name
        self.type = type
        self.images = images
        self.createdAt = createdAt
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Int.self, forKey: "id")
        self.name = try values.decode(String.self, forKey: "name")
        self.type = try values.decode(Int.self, forKey: "type")
        self.images = try values.decodeIfPresent(PersonImages.self, forKey: "images")
        self.createdAt = try values.decode(Date.self, forKey: "created_at")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(name, forKey: "name")
        try values.encode(type, forKey: "type")
        try values.encodeIfPresent(images, forKey: "images")
        try values.encode(createdAt, forKey: "created_at")
    }
}
