// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// SubjectRelation
public struct V0SubjectRelation: Codable {
    public var id: Int
    public var type: Int
    public var name: String
    public var nameCn: String
    public var images: Images?
    public var relation: String

    public init(id: Int, type: Int, name: String, nameCn: String, images: Images? = nil, relation: String) {
        self.id = id
        self.type = type
        self.name = name
        self.nameCn = nameCn
        self.images = images
        self.relation = relation
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Int.self, forKey: "id")
        self.type = try values.decode(Int.self, forKey: "type")
        self.name = try values.decode(String.self, forKey: "name")
        self.nameCn = try values.decode(String.self, forKey: "name_cn")
        self.images = try values.decodeIfPresent(Images.self, forKey: "images")
        self.relation = try values.decode(String.self, forKey: "relation")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(type, forKey: "type")
        try values.encode(name, forKey: "name")
        try values.encode(nameCn, forKey: "name_cn")
        try values.encodeIfPresent(images, forKey: "images")
        try values.encode(relation, forKey: "relation")
    }
}
