module: BangumiKit
generate:
- entities
- paths
- enums
dataTypes:
  integer:
    int32: Int
    int64: Int
  string:
    uuid: String
    SpecialFeatureType: SpecialFeatureType
entities:
  protocols: ["Codable", "Hashable"]
  includeIdentifiableConformance: true
  sortPropertiesAlphabetically: true
  exclude:
  - BaseItemDto.CurrentProgram # removed due to circular references for struct conformance
paths:
  style: operations
  filenameTemplate: "%0API.swift"