// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// 虚拟角色
public struct LegacyCharacter: Codable, Hashable {
    /// 人物
    public var legacyMono: LegacyMono
    /// 声优列表
    public var actors: [LegacyMonoBase]?
    /// 人物信息
    public var info: LegacyMonoInfo?

    public init(legacyMono: LegacyMono, actors: [LegacyMonoBase]? = nil, info: LegacyMonoInfo? = nil) {
        self.legacyMono = legacyMono
        self.actors = actors
        self.info = info
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.legacyMono = try LegacyMono(from: decoder)
        self.actors = try values.decodeIfPresent([LegacyMonoBase].self, forKey: "actors")
        self.info = try values.decodeIfPresent(LegacyMonoInfo.self, forKey: "info")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(legacyMono, forKey: "legacyMono")
        try values.encodeIfPresent(actors, forKey: "actors")
        try values.encodeIfPresent(info, forKey: "info")
    }
}
