// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// 现实人物
public struct LegacyPerson: Codable, Hashable {
    /// 人物
    public var legacyMono: LegacyMono
    /// 人物信息
    public var info: LegacyMonoInfo?

    public init(legacyMono: LegacyMono, info: LegacyMonoInfo? = nil) {
        self.legacyMono = legacyMono
        self.info = info
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.legacyMono = try LegacyMono(from: decoder)
        self.info = try values.decodeIfPresent(LegacyMonoInfo.self, forKey: "info")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(legacyMono, forKey: "legacyMono")
        try values.encodeIfPresent(info, forKey: "info")
    }
}
