// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// An enumeration.
public enum PersonCareer: String, Codable, CaseIterable {
    case producer
    case mangaka
    case artist
    case seiyu
    case writer
    case illustrator
    case actor
}
