// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Revision: Codable, Hashable, Identifiable {
    public var createdAt: Date
    /// 意义同<a href="#model-Me">Me</a>
    public var creator: Creator?
    public var id: Int
    public var summary: String
    public var type: Int

    public init(createdAt: Date, creator: Creator? = nil, id: Int, summary: String, type: Int) {
        self.createdAt = createdAt
        self.creator = creator
        self.id = id
        self.summary = summary
        self.type = type
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.createdAt = try values.decode(Date.self, forKey: "created_at")
        self.creator = try values.decodeIfPresent(Creator.self, forKey: "creator")
        self.id = try values.decode(Int.self, forKey: "id")
        self.summary = try values.decode(String.self, forKey: "summary")
        self.type = try values.decode(Int.self, forKey: "type")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(createdAt, forKey: "created_at")
        try values.encodeIfPresent(creator, forKey: "creator")
        try values.encode(id, forKey: "id")
        try values.encode(summary, forKey: "summary")
        try values.encode(type, forKey: "type")
    }
}
