// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct RevisionExtra: Codable, Hashable {
    /// Image
    public var img: String?

    public init(img: String? = nil) {
        self.img = img
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.img = try values.decodeIfPresent(String.self, forKey: "img")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(img, forKey: "img")
    }
}
