// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Get Character Image
    static public func getCharacterImageByID(characterID: Int, type: String) -> Request<Void> {
        Request(path: "/v0/characters/\(characterID)/image", method: "GET", query: [("type", type)], id: "getCharacterImageById")
    }
}
