// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Get Episode Revision
    static public func getEpisodeRevisionByRevisionID(revisionID: Int) -> Request<BangumiKit.DetailedRevision> {
        Request(path: "/v0/revisions/episodes/\(revisionID)", method: "GET", id: "getEpisodeRevisionByRevisionId")
    }
}
