// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Get Person
    ///
    /// Cache with 60s
    static public func getPersonByID(personID: Int) -> Request<BangumiKit.PersonDetail> {
        Request(path: "/v0/persons/\(personID)", method: "GET", id: "getPersonById")
    }
}
