// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Get Person Image
    static public func getPersonImageByID(personID: Int, type: String) -> Request<Void> {
        Request(path: "/v0/persons/\(personID)/image", method: "GET", query: [("type", type)], id: "getPersonImageById")
    }
}
