// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Get Subject Persons
    static public func getRelatedPersonsBySubjectID(subjectID: Int) -> Request<[BangumiKit.RelatedPerson]> {
        Request(path: "/v0/subjects/\(subjectID)/persons", method: "GET", id: "getRelatedPersonsBySubjectId")
    }
}
