// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Get Subject Revision
    static public func getSubjectRevisionByRevisionID(revisionID: Int) -> Request<BangumiKit.SubjectRevision> {
        Request(path: "/v0/revisions/subjects/\(revisionID)", method: "GET", id: "getSubjectRevisionByRevisionId")
    }
}
