// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// 获取用户角色收藏列表
    static public func getUserCharacterCollections(username: String) -> Request<BangumiKit.PagedUserCharacterCollection> {
        Request(path: "/v0/users/\(username)/collections/-/characters", method: "GET", id: "getUserCharacterCollections")
    }
}
