// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// 更新章节收藏信息
    static public func putUserEpisodeCollection(episodeID: Int, type: Int) -> Request<Void> {
        Request(path: "/v0/users/-/collections/-/episodes/\(episodeID)", method: "PUT", body: ["type": type], id: "putUserEpisodeCollection")
    }
}
