// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Uncollect character for current user
    ///
    /// 为当前用户取消收藏角色
    static public func uncollectCharacterByCharacterIDAndUserId(characterID: Int) -> Request<Void> {
        Request(path: "/v0/characters/\(characterID)/collect", method: "DELETE", id: "uncollectCharacterByCharacterIdAndUserId")
    }
}
